### ISSUE TITLE
Set syslog identifier and syslog PID fields?

### ISSUE THREAD

**Issue by swsnr** [slog-rs/journald#12]
syslog identifier normally gets set to the short invocation name, i.e. the filename of `std::env::current_exe`, and allows filtering with `journalctl -t`.

**Comment by tmccombs** [comment]
SYSLOG_IDENTIFIER does seem to be automatically set to the short invocation name. Either by systemd-journald itself, or by the call to `sd_journal_sendv`.  Also, the PID is available as the `_PID` field in the journal. 

It is also quite possible to specify these yourself, with something like:


```rust
let root = Logger::rot(JournaldDrain.ignore_res(), o!("SYSLOG_IDENTIFIER" => short_name, "SYSLOG_PID" => std::proces::id)
```

where `shortname` is the short invocation name.

**Comment by swsnr** [comment]
I also noticed that libsystemd seems to set the identifier itself.

I guess we can close this; I'm sorry for the noise.
