### ISSUE TITLE
Please update libsystemd-sys dependency

### ISSUE THREAD

**Issue by paulvt** [slog-rs/journald#14]
I am working on an application which also uses the `ystemd` crate for other things.
This crate, and its depend `libsystemd-sys` has received many updates over the past months.

Could the dependency on `libsystemd-sys` be bumped to `libsystemd-sys = "0.8"` as suggested by their README.
I have tested that all tests pass if you do this.

**Comment by dpc** [comment]
:+1: but PR please :)
