### ISSUE TITLE
Provide alternative libsystemd backend?

### ISSUE THREAD

**Issue by Kixunil** [slog-rs/journald#9]
I wonder if providing an alternative to `libsystemd-sys` would be an accepted change. I have a crate that uses the pure-Rust `libsystemd` as a dependency and it'd be nice not having to duplicate the code if this crate is used as well.

**Comment by tmccombs** [comment]
I'm open to the idea. It should probably be controlled with a feature flag.  Iirc, when I initially implemented this, there wasn't a feature comlete rust-only systemd library.

**Comment by Kixunil** [comment]
Yes, definitely a feature flag. I will look at it at some point.

**Comment by Kixunil** [comment]
Thinking about it a bit again, maybe having a separate facade crate would be helpful for others as well? Although in that case, I'd probably prefer to use pure Rust library.

**Comment by tmccombs** [comment]
version 2.2 was just released which uses libystemd as its backend.

**Comment by Kixunil** [comment]
Thanks!
